spring:
  application:
    name: demo-spring-cloud-alibaba-sentinel

  main:
    allow-circular-references: true

  cloud:
    sentinel:
      enabled: true
#      log:
#        dir: logs/csp/
#        switch-pid: true
      transport:
#        dashboard: 10.255.23.26:8849
        dashboard: localhost:8849
#        port: 8719
#        heartbeat-interval-ms: 30000

management:
  endpoints:
    web:
      exposure:
        include: '*'