server:
  port: 9002

spring:
  application:
    name: spring-cloud-admin-client
  boot:
    admin:
      client:
        url: http://localhost:8901

management:
  endpoints:
    web:
      exposure:
        include: '*'
