server:
  port: 9102
spring:
  application:
    name: concumser-service
  main:
    allow-circular-references: true
  cloud:
    sentinel:
      enabled: true
      log:
        dir: logs/csp/
        switch-pid: true
      transport:
        dashboard: 10.255.23.26:8849
        port: 8719
        heartbeat-interval-ms: 30000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

#feign.
feign:
  client:
    config:
      default:
        connectTimeout: 1000
        readTimeout: 1000
        loggerLevel: full
        decode404: false
        metrics.enabled: false
        retryer: com.fengwenyi.springclouddemo.demospringcloudfeignsentinel.consumerservice.MyRetryer
      provider-get:
        connectTimeout: 1000
        readTimeout: 6000
      provider-post:
        connectTimeout: 1000
        readTimeout: 20000
  okhttp:
    enabled: true
  sentinel:
    enabled: true