server:
  port: 10101

spring:
  application:
    name: demo-spring-cloud-nacos-discovery
  cloud:
    nacos:
      server-addr: localhost:8848
      username: nacos
      password: nacos
      discovery:
        namespace: demo
        group: spring-cloud
