server:
  port: 8001

spring:
  application:
    name: demo-spring-cloud-dubbo-provider-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

  main:
    allow-circular-references: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

dubbo:
  # 配置注册中心
  registry:
    address: spring-cloud://127.0.0.1:8848
  protocol:
    id: dubbo
    name: dubbo
    port: 20881
  scan:
    base-packages: com.fengwenyi.springcloud.dubbo.sdk.service
