server:
  port: 8001

spring:
  application:
    name: demo-spring-cloud-dubbo-provider-service

  main:
    allow-circular-references: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
